# Generated by Django 4.2.2 on 2023-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default='YYYY-MM-DD')),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(default='null', max_length=100)),
                ('phn', models.IntegerField(default=1234567890)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('add', models.CharField(default='null', max_length=255)),
                ('depart', models.CharField(default='null', max_length=100)),
                ('course', models.CharField(default='null', max_length=100)),
                ('purpose', models.CharField(default='null', max_length=100)),
                ('material', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
